# Generated by Django 4.2.7 on 2025-11-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_social_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrapingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('selectors', models.JSONField(default=dict, help_text='CSS selectors or XPath expressions')),
                ('method', models.CharField(choices=[('beautifulsoup', 'BeautifulSoup (HTML)'), ('css', 'CSS Selector'), ('xpath', 'XPath'), ('selenium', 'Selenium (JavaScript)')], default='beautifulsoup', max_length=20)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('wait_time', models.FloatField(default=0, help_text='Wait time in seconds before scraping')),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_value', models.TextField()),
                ('selector', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='company_social_finder.webscrapingrequest')),
            ],
            options={
                'ordering': ['request', 'field_name'],
            },
        ),
    ]
