# Generated by Django 4.2.7 on 2025-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_social_finder', '0002_webscrapingrequest_webscrapingresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkWebScrapingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.JSONField(help_text='List of URLs to scrape')),
                ('selectors', models.JSONField(default=dict, help_text='CSS selectors or XPath expressions')),
                ('method', models.CharField(default='beautifulsoup', max_length=20)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('wait_time', models.FloatField(default=0)),
                ('total_urls', models.IntegerField(default=0)),
                ('completed_urls', models.IntegerField(default=0)),
                ('failed_urls', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, help_text='Combined results from all URLs', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
