# Generated by Django 4.2.7 on 2025-11-26 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_social_finder', '0003_bulkwebscrapingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkwebscrapingrequest',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for this scraping request', max_length=255),
        ),
        migrations.AddField(
            model_name='bulkwebscrapingrequest',
            name='urls_file',
            field=models.FileField(blank=True, help_text='Upload a CSV or TXT file with URLs (one per line)', null=True, upload_to='bulk_inputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])]),
        ),
        migrations.AddField(
            model_name='bulkwebscrapingrequest',
            name='urls_text',
            field=models.TextField(blank=True, help_text='Paste URLs here, one per line'),
        ),
        migrations.AlterField(
            model_name='bulkwebscrapingrequest',
            name='urls',
            field=models.JSONField(blank=True, help_text='List of URLs to scrape (legacy)', null=True),
        ),
    ]
