# Generated by Django 4.2.7 on 2025-11-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_social_finder', '0004_bulkwebscrapingrequest_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapingRequest',
        ),
    ]
