# Generated by Django 4.2.7 on 2025-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
