# Generated by Django 5.0.4 on 2025-12-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_input_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('homepage_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('homepage_detection', models.CharField(blank=True, max_length=50, null=True)),
                ('ads_txt_result', models.JSONField(blank=True, null=True)),
                ('app_ads_txt_result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='jobs.job')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job'], name='jobs_jobres_job_id_041864_idx'), models.Index(fields=['original_url'], name='jobs_jobres_origina_cf0b46_idx')],
            },
        ),
    ]
