# Generated by Django 5.0.4 on 2025-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stats_ads_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stats_ads_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stats_app_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stats_app_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stats_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
