# Generated by Django 5.0.4 on 2025-12-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_stats_ads_error_job_stats_ads_success_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobresult',
            index=models.Index(fields=['job', 'original_url'], name='jobs_jobres_job_id_634645_idx'),
        ),
    ]
