# Generated by Django 4.2.7 on 2025-11-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceScrapingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(help_text='URLs to scrape, one per line or comma-separated')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, help_text='Scraped product data', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('other', 'Other')], max_length=50)),
                ('product_url', models.URLField(max_length=2000, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='ASIN, eBay Item ID, etc.', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_scraped_at'],
                'indexes': [models.Index(fields=['platform', '-last_scraped_at'], name='ecommerce_s_platfor_4d4c5d_idx'), models.Index(fields=['external_id'], name='ecommerce_s_externa_a7cd86_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('availability', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='ecommerce_scraper.product')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['product', '-scraped_at'], name='ecommerce_s_product_129495_idx')],
            },
        ),
    ]
