# Generated by Django 4.2.7 on 2025-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercescrapingrequest',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('daraz', 'Daraz'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('daraz', 'Daraz'), ('other', 'Other')], max_length=50),
        ),
    ]
