# Generated by Django 4.2.7 on 2025-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_scraper', '0002_alter_ecommercescrapingrequest_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercescrapingrequest',
            name='custom_selectors',
            field=models.JSONField(blank=True, help_text="Custom CSS selectors: {'title': '...', 'price': '...', etc.}", null=True),
        ),
        migrations.AlterField(
            model_name='ecommercescrapingrequest',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('daraz', 'Daraz'), ('other', 'Other (Generic)')], default='other', help_text='Platform name (for metadata only - scraping works with any site)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopify', 'Shopify'), ('aliexpress', 'AliExpress'), ('etsy', 'Etsy'), ('daraz', 'Daraz'), ('other', 'Other (Generic)')], max_length=50),
        ),
    ]
